### ISSUE TITLE
ERROR: invalid password

### ISSUE THREAD

**Issue by DrEvil35** [kov-serg/get-cpcert#2]
Hello! I was building this utility for the Windows system. As a result, I get an incorrect password error on the samples.

An attempt to build a system for Linux did not result in an error solution. 
However, the binary release version works well.

I am using 
dev-libs / openssl-1.1.1i
dev-libs / gost-engine-1.1.0.3_p20181031-r1

**Comment by kov-serg** [comment]
Openssl doesn't preserve back compatibility, in common manner. So to compile with new version every step should carefully be verified.

**Comment by DrEvil35** [comment]
I've done some research. And I found out that the gost-engine works correctly with a binary assembly. Unfortunately, nothing can be found out about libcrypto. The executable is built statically.

Looks like you are right about OpenSSL. But it's hard for me to understand which stage fails.

**Comment by kov-serg** [comment]
I compile it for windows with openssl1.1.1c and 1.1.1i
yes it fails for gost256/512 but work for gost89.
Now is to late to go deper. I'll see it in more details in a week.

**Comment by DrEvil35** [comment]
I also discovered my mistake. Compiling libgost with static libcrypto.a results in an invalid hash calculation

**Comment by DrEvil35** [comment]
Hi, I've made builds for different systems. The problem was BE LE
[build.tar.gz](https://github.com/kov-serg/get-cpcert/files/5865037/build.tar.gz)

**Comment by kov-serg** [comment]
Yes. gost engine should be build with -DL_ENDIAN macros defined. With out this macros hash2012 works wrong on x86
