### ISSUE TITLE
Does it work for crypto-pro 5?

### ISSUE THREAD

**Issue by iliakan** [kov-serg/get-cpcert#3]

**Comment by kov-serg** [comment]
Just try. I think it should not denend on version of crypto pro.

**Comment by iliakan** [comment]
Is Mac supported? Or Linux only?

**Comment by kov-serg** [comment]
If you compile it for macos it will work. But you should compile dependences first (openssl-1.1.1 and gost-engine). For windows it cause no problem. But I never try it for macos.
I use this utility on server with linux, so no real need in other platforms for me.
It simply converts binary key backup from crypto pro (platform independent) to pem file with certificate and private key.

**Comment by iliakan** [comment]
I tried it on Debian for CSP 5.0, and it worked.

Not sure about Mac.

What really bothers me is that your utility changes system files.

When one runs something like `prepare.sh`, no such changes are expected.

**Comment by iliakan** [comment]
More than that. I wouldn't expect from an utility, such as yours, to alter **any** system files at all ;).

**Comment by kov-serg** [comment]
It's because of openssl. I am rewriting it to have no dependences, but it's not ready yet.

**Comment by iliakan** [comment]
Are you sure you can't leave libs somewhere under the project folder?
Not install them on system path.

P.S. Thank you very much for this great tool. I struggled for quite some time before I found it.
