### ISSUE TITLE
Streams are unsupported

### ISSUE THREAD

**Issue by iliakan** [kov-serg/get-cpcert#5]
Что означает такая ошибка?

```
ERROR: streams are unsupported
```

**Comment by iliakan** [comment]
Можно ли что-то сделать, чтобы её обойти?

**Comment by kov-serg** [comment]
У вас сертификат с записями с неизвестной длинной.
Что сделать: добавить стримы надо. Можете прислать сертификат со стримами?

**Comment by kov-serg** [comment]
Попробуйте такие изменения внести.
```
static int asn1_parse_tag(packet_t *p,
  asn1_parser_cfg_t *cfg,
  asn1_parser_tag_t *parent,
  int stream)
{
  enum {
    ASN1_MASK_MULTI=0x20, ASN1_MASK_TYPE=0x1F,
    ASN1_MASK_CLASS=0xC0, ASN1_SHIFT_CLASS=6
  };
  asn1_parser_tag_t tag[1];packet_t ps[1];int rc;

  tag->index=0;
  tag->level=parent ? parent->level+1 : 0;
  while(!pkt_end(p)) {
    if (stream) {
      if (p->pos+1<p->size && p->data[p->pos]==0 && p->data[p->pos+1]==0) {
        p->pos+=2; break;
      }
    }
    tag->tag_pos=p->pos;
    tag->tag=pkt_get(p);
    tag->tag_type=tag->tag&ASN1_MASK_TYPE;
    if (tag->tag_type==ASN1_MASK_TYPE) tag->tag_type=asn1_num(p);
    tag->tag_class=(tag->tag&ASN1_MASK_CLASS)>>ASN1_SHIFT_CLASS;
    tag->tag_composite=tag->tag&ASN1_MASK_MULTI;
    tag->tag_len=asn1_len(p);
    if (tag->tag_len==0) { // stream
      pkt_sub(ps,p,pkt_left(p));
      if (tag->tag_composite) rc=asn1_parse_tag(ps,cfg,tag,1); else {
        for(rc=2;ps->pos<ps->size;) {
          while(ps->pos<ps->size && ps->data[ps->pos]!=0) ps->pos++;
          if (ps->pos+1<ps->size && ps->data[++ps->pos]==0) { 
            ps->pos++; rc=0; break;
          }
        }
      }
      if (rc) return rc;
      tag->tag_len=ps->pos-p->pos-2;
      pkt_sub(tag->body,p,tag->tag_len);
      rc=cfg->tag(cfg->tag_ctx,tag); if (rc) return rc;
      p->pos=ps->pos;
    } else {
      pkt_sub(tag->body,p,tag->tag_len);
      rc=cfg->tag(cfg->tag_ctx,tag); if (rc) return rc;
      if (tag->tag_composite) {
        pkt_sub(tag->body,p,tag->tag_len);
        rc=asn1_parse_tag(tag->body,cfg,tag,0); if (rc) return rc;
      }
      pkt_skip(p,tag->tag_len);
    }
    tag->index++;
  }
  return 0;
}
int asn1_parse(packet_t *p,asn1_parser_cfg_t *cfg) { 
  return asn1_parse_tag(p,cfg,0,0); 
}
```

**Comment by gelezayka** [comment]
похоже новые ЭЦП в этом году подложили какую-то мину :(

добавил выше код
теперь
ERROR: parse primary

**Comment by gelezayka** [comment]
новые файлы:
-rwxr-xr-x  1 anton  wheel  2390 15 февр. 14:14 header.key
-rwxr-xr-x  1 anton  wheel    60 15 февр. 14:14 masks.key
-rwxr-xr-x  1 anton  wheel    60 15 февр. 14:14 masks2.key
-rwxr-xr-x  1 anton  wheel   300 15 февр. 14:14 name.key
-rwxr-xr-x  1 anton  wheel    70 15 февр. 14:14 primary.key
-rwxr-xr-x  1 anton  wheel    70 15 февр. 14:14 primary2.key

старые файлы:
-rw-r--r--   1 anton  wheel  3627 18 мая    2021 header.key
-rw-r--r--   1 anton  wheel    56 18 мая    2021 masks.key
-rw-r--r--   1 anton  wheel    56 18 мая    2021 masks2.key
-rw-r--r--   1 anton  wheel    58 18 мая    2021 name.key
-rw-r--r--   1 anton  wheel    36 18 мая    2021 primary.key
-rw-r--r--   1 anton  wheel    36 18 мая    2021 primary2.key


masks и primary прям изменили размеры

**Comment by gelezayka** [comment]
Ну и дальнейшее изучение показало, что в masks 4 байта лишних нулей каких-то и в primary 34 байта каких-то нулей

**Comment by gelezayka** [comment]
коцнул их через truncate, все вынулось без проблем, вывод:

замена кода выше + truncate = все работает

**Comment by kov-serg** [comment]
Очень сумбурно. 
1. новые сертификаты со стримами?
2. просто нули в конце или еще какие-то тонкости есть?

ps: Я пока поставил ключи от астрала они на 3года. Так такого еще небыло.

**Comment by gelezayka** [comment]
Ну как есть, вот сегодня как раз вынимал/делал pem из нового подарка который мне принесли.
как и писал выше пришлось изменить код, как выше, и нули truncate сделать.

Завтра еще будут свежие ключики, погляжу как у них все будет, если чего отпишусь.

**Comment by iliakan** [comment]
@gelezayka это новый ключ ФНС?

**Comment by gelezayka** [comment]
Завтра уточню, вроде как да, но там еще и Сбер тоже выдает эти токены, мол вставьте токен, идите в отделение, теперь опять вставьте токен, он после этого еще туда второй приватный ключ ухает :-)

**Comment by gelezayka** [comment]
ЭЦП которую выдали через Сбер, прекрасно экспортировали и без всяких truncate вынули все.

**Comment by Buzzlay** [comment]
@gelezayka @kov-serg 
> ЭЦП которую выдали через Сбер, прекрасно экспортировали и без всяких truncate вынули все.

Здравствуйте, можете подсказать, что я делаю не так?
До добавления кода описанного выше выдавалось две ошибки:
*ERROR: streams are unsupported
*ERROR: parse primary
Вставил код, как написано выше, удалил get-cpcert и libgost.so, заново запустил build.sh и далее по инструкции скормил папку с 6ю файлами get-cpcert.
Получил такие ошибки:
*ERROR: invalid password
*ERROR: unable to get privkey
P.S. Если есть возможность, то прошу связаться со мной по эл. почте eburgruss@gmail.com - это очень срочно, так как у нас вся система встанет без этого pfx.
...

**Comment by iliakan** [comment]
Наверно имеет смысл уточнить, откуда ключ.

Тоже Сбер?

Best regards,
Ilya Kantor

**Comment by kov-serg** [comment]
Добавил стримы в исходники. Я подозреваю что там такая же беда и надо немного [укоротить файлы](https://github.com/kov-serg/get-cpcert/issues/5#issuecomment-1040354104).

**Comment by Buzzlay** [comment]
@iliakan ФНС

**Comment by kov-serg** [comment]
Там такая же ситуация
```
drwxrwxr-x 2 fkr fkr 4096 февр. 17 04:09 .
drwxrwxr-x 4 fkr fkr 4096 февр. 17 04:42 ..
-rw-rw-r-- 1 fkr fkr 2718 февр. 17 04:05 header.key
-rw-rw-r-- 1 fkr fkr   60 февр. 17 04:05 masks2.key
-rw-rw-r-- 1 fkr fkr   60 февр. 17 04:05 masks.key
-rw-rw-r-- 1 fkr fkr  300 февр. 17 04:05 name.key
-rw-rw-r-- 1 fkr fkr   70 февр. 17 04:05 primary2.key
-rw-rw-r-- 1 fkr fkr   70 февр. 17 04:05 primary.key
```

Можно попробывать укоротить.
dd if=primary2.key of=primary.key bs=36 count=1
dd if=mask2.key of=mask.key bs=56 count=1

У меня живого образца нет, думаю лучше спросить у [iliakan](https://github.com/iliakan)
Или напишите получилось или нет.

**Comment by kov-serg** [comment]
Добавил в исходники автоматическое обрезание по длинне. Теперь должно сразу работать. Без dd

ps: стримов там не оказалось (очень жаль). просто файлы дополнены 0xFF-ами

**Comment by Buzzlay** [comment]
@kov-serg Всё работает, будем проверять работоспособность полученных файлов, спасибо огромное!

**Comment by kov-serg** [comment]
Вместо обрезки файлов сделал ограничение на 1 корневой элемент. Теперь работает не зависимо от длинны файлов и для 512битных ключей.
Просто будет выводить предупреждение
```
WARNING: primary size 36 of 70, mask size 56 of 60
```
