### ISSUE TITLE
Support cryptopro .pfx files?

### ISSUE THREAD

**Issue by ethaniel** [kov-serg/get-cpcert#6]
Hello!

I have a file .pfx exported from CryptoPro. Is there a way how I can use get-cpcert to convert it into .pem?

**Comment by kov-serg** [comment]
No, there is no way. pfx files from crypto pro does not contain private key.

**Comment by ethaniel** [comment]
They do. When I get a new certificate in a token, I import it into Cryptopro, then export it with the key inside before transferring to another machine.

![image](https://user-images.githubusercontent.com/941973/150641710-2cd8f26a-2e11-40a6-9541-ed280984d1df.png)
![image](https://user-images.githubusercontent.com/941973/150641720-0e08d109-d6a9-4434-bb33-2cb0b0c2f5bc.png)

**Comment by kov-serg** [comment]
Вы потом попробуйте импортировать. Я когда пробывал закрытого ключа там не было даже когда эту галочку ставил.

ps: случайно нажал close issue :(

**Comment by ethaniel** [comment]
Вот вчера перетаскивал файл с одной винды на другую, где есть p12fromgostcsp. "Экспортировать все расширенные свойства" оставил опцию выключенной и при экспорте ключа указал пароль. Тогда все успешно перенеслось и записалось в реестр новой машины. Затем через p12fromgostcsp получил нормальный файл, который уже затем перенес в линукс и через openssl смог сконвертировать в .pem. Несколько лет уже так делаю с разными ключами. Это ЭЦП, выданная на имя директора организации.

**Comment by kov-serg** [comment]
Ну незнаю. Это работало когда был старый гост. Оно в pfx ложило свой киптопровский контейнер неизвестного формата.
Возможно оно имеет похожий формат с бэкапом. Но для экпорта на другую машину, можно просто из виндового рееcтра скопировать и не заморачиваться.

**Comment by li0ard** [comment]
Для PFX от КриптоПро есть моя утилита - cpfx. Есть версия на [Go](https://github.com/li0ard/cpfx_go) и на [Python](https://github.com/li0ard/cpfx)
