### ISSUE TITLE
Как запустить?

### ISSUE THREAD

**Issue by rostislaved** [kov-serg/get-cpcert#7]
Привет!
У меня есть .pfx файл, который я пытаюсь скормить программе вот так:
`./get-cpcert 1.pfx 0000 > certificate.pem`

И получаю:
`ERROR: read header`

Как это сделать правильно?

Немного контекста про 1.pfx
Обычно я с 1.pfx работаю следующим образом:
1. Устанавливаю его в винду просто два раза кликая (вроде для этого нужен КриптоПро)
2. Через  P12FromGostCSP.exe получаю уже нормальный .pfx файл
3. Через пропатченный openssl (это уже на линуксе) получаю приватный ключ и сертификат.

**Comment by kov-serg** [comment]
Не неправильно. она не работает с pfx файлами.

1. вставляете флешку
2. в криптопро делаете экспорт на флешку
3. и вот на флешке будет директория с несколькими файлами
4. путь к ней и надо скармливать и пароль который устанавливаете при экспорте

ps: посмотрите примеры в архиве

**Comment by rostislaved** [comment]
Да, сработало, спасибо.
Получилось дефолтными средствами винды экспортировать. Экспортировалось сюда:
C:\Users\Admin\AppData\Local\Crypto Pro\OOOrrVAY.000

Но установленный криптоПро все равно нужен.

А есть способы исключить необходимость криптоПро? Хочется все это проделывать на линуксе. Ну или хотя бы на винде, но без криптоПро


Или. Возможно ли сделать на линуксе чем-то операцию, которую делает P12FromGostCSP.exe? То есть из одного .pfx файла делает другой pfx файл, который уже может быть использован пропатченным openssl?
