### ISSUE TITLE
error: ln libssl

### ISSUE THREAD

**Issue by PiVirus** [kov-serg/get-cpcert#8]
Приветствую! Ubuntu 20.04 во время работы prepare.sh возникает ошибка:
ln: не удалось создать символьную ссылку '/lib/x86_64-linux-gnu/libssl.so.1.1': Файл существует
ERROR: ln libssl
Ни убрать и переименовать этот файл не получается. Как обойти эту ошибку?

**Comment by kov-serg** [comment]
У меня оно собиралось под ubuntu 14.04 и 10 и обновляло openssl что бы php могло его использовать.
Но можно не устанавливать в систему, а просто собрать.
Более того вы можете взять просто бинарник из релиза и его использовать.

**Comment by PiVirus** [comment]
Просто собрать пробовал, не дает, говорит нет gost.so? lgost_core, lgost. Господи, почему я не увидел архив с бинарником. Спасибо за подсказку, попробую

**Comment by PiVirus** [comment]
Все отлично получилось, на выходе certifiate.pem из папки с ключами. Проверено на ubuntu 20.04
